title: "Book Example"
summary: "説明"
topics: ["JavaScript"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 001_000_comment_console
  - 001_001_data
  - 001_002_variables
  - 001_003_calculate
  - 001_004_getting_ready
